---
  - name: Ansible Vault Testing
    hosts: allservers
    become: yes
    become_user: root
    no_log: True
    vars:
     user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34356161363038633432396263616263663961643430666235353733383034333735393763663362
          3133323464646262656233356632333764376165363536660a396366666132666563386262326133
          63613861393936336631623939656261376562323964316262343738386366626362306136326565
          6465303966636533360a633034383131313566353861336464333336653132303966386330653237
          6131
    tasks:
      - name: Create .aws folder
        shell: mkdir -p /root/.aws
        ignore_errors: yes
      - name: Replace Password Authentication To Yes
        ansible.builtin.lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PasswordAuthentication no'
          line: PasswordAuthentication yes
          backup: yes
        notify:
        -  Restart SSH Service
      - name: Copy Encrypted File To /tmp
        copy:
          src: /home/ansibleadmin/terraform-ansible/aws_creds #This Encrypted File Must Be Created Prior To Running The Playbook.
          dest: /tmp/aws_creds
          owner: root
          group: root
          mode: '0600'
      - name: Copy Encrypted File To .aws folder
        copy:
          src: /home/ansibleadmin/terraform-ansible/aws_creds #This Encrypted File Must Be Created Prior To Running The Playbook.
          dest: /root/.aws/credentials
          owner: root
          group: root
          mode: '0600'
      - name: Creating adminuser
        user:
          name: naveen
          state: present
          comment: Admin User naveen
          groups: root
          shell: /bin/bash
          group: root
          password: "{{ '%s' | format(user_password) | regex_replace('\n', '') | password_hash('sha512') }}"
          password_expire_min: 1
      - name: print the secure variable
        debug:
         var: user_password
      - name: Restart SSH Service
        shell: sudo service sshd restart
    handlers:
      - name: Restart SSH Service
        shell: sudo service sshd restart


    