#https://medium.com/splunkuserdeveloperadministrator/creating-mysql-databases-with-ansible-925ab28598ab

---
- name: Install MySQL Using Ansible Role
  hosts: private
  become: yes
  become_user: root
  roles:
  - { role: geerlingguy.mysql }
  tasks:
  - name: create a new database 
    mysql_db: >
      name=myflixdb 
      state=present 
      login_user=root
    tags:
    - mysql
  - name: add sample data to database 
    copy: src=dump.sql dest=/tmp/dump.sql
    tags:
    - mysql
  - name: insert sample data into database
    mysql_db: name=myflixdb state=import target=/tmp/dump.sql
    tags:
    - mysql
  - name: Add records to MySQL
    mysql_db: name=myflixdb state=import target=/tmp/dump.sql
    tags:
    - mysql
    

  