---
- hosts: private
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: ansible copy file from remote to local
    fetch:
     src: /var/www/html/index.nginx-debian.html
     dest: /tmp

